name: Pipeline de Automação de Vídeos

on:
  schedule:
    # Executa às 5:00 AM e 7:00 PM de São Paulo (BRT - UTC-3)
    - cron: '0 8 * * *'  # 5:00 AM BRT → 8:00 AM UTC
    - cron: '0 22 * * *' # 7:00 PM BRT → 10:00 PM UTC
  workflow_dispatch:  # Gatilho manual para testes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do Código
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      # Passo 2: Configurar Python
      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Passo 3: Instalar Dependências
      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Configurar Variáveis de Ambiente
      - name: Configurar Variáveis de Ambiente
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
          TIKTOK_EMAIL: ${{ secrets.TIKTOK_EMAIL }}
          TIKTOK_SENHA: ${{ secrets.TIKTOK_SENHA }}
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
        run: |
          echo "GEMINI_API_KEY=${GEMINI_API_KEY}" >> $GITHUB_ENV
          echo "YOUTUBE_CHANNEL_ID=${YOUTUBE_CHANNEL_ID}" >> $GITHUB_ENV
          echo "TIKTOK_EMAIL=${TIKTOK_EMAIL}" >> $GITHUB_ENV
          echo "TIKTOK_SENHA=${TIKTOK_SENHA}" >> $GITHUB_ENV
          echo "PIXABAY_API_KEY=${PIXABAY_API_KEY}" >> $GITHUB_ENV

      # Passo 5: Executar o Pipeline
      - name: Executar Pipeline
        run: |
          python run_pipeline.py

      # Passo 6: Armazenar Artefatos (Opcional)
      - name: Upload de Logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: scripts/generate_theme.log
